export const metadata = {
  title: 'thau haru',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (<div>
    { children }
    </div>
  );
}
