import { Geist, Geist_Mono } from 'next/font/google';
import Menubar from '@/components/layout/Menubar';
import Footer from '@/components/layout/Footer';
import Navbar from '@/components/layout/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: '',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <header>
          <Navbar />
        </header>

        <div className="body flex-1 flex">
          <aside className="flex-1/5 ">
            <Menubar />
          </aside>
          <main className="flex-4/5 ">{children}</main>
        </div>

        <footer>
          <Footer />
        </footer>
      </div>
  );
}
